name: Build Rust Doc

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build doc
        run: |
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2022S.git user
          cd os
          make
          cargo doc --no-deps --verbose
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./os/target/riscv64gc-unknown-none-elf/doc
          destination_dir: ${{ github.ref_name }}
